name: Test
on: [push]
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  test:

    services:
      db:
        image: postgres:14.7
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.1'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Format
        run: bundle exec standardrb

      - name: Copy config
        run: |
          cp config/database.yml.example config/database.yml

      - name: Run tests
        env:
          COV: 1
          DB_HOST: 127.0.0.1
          DB_PASSWORD: postgres
          DB_USER: postgres
          RAILS_ENV: test
        run: |
          bundle exec rake db:create db:schema:load
          bundle exec rspec -p

